# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: java:latest

services:
  - postgres:9.4
  - galacticfog/test-ldap:latest

variables:
  POSTGRES_DB: gestalt-security
  POSTGRES_USER: gestaltdev
  POSTGRES_PASSWORD: letmein
  DATABASE_HOSTNAME: postgres
  DATABASE_NAME: gestalt-security
  DATABASE_PORT: 9455
  DATABASE_USERNAME: gestaltdev
  DATABASE_PASSWORD: letmein
  ROOT_USERNAME: root
  ROOT_PASSWORD: letmein
  TEST_LDAP_URL: ldap://test-ldap:389
  
build:
  stage: build
  script:
    - ./activator clean update
    
  stage: test
  script:
    - ./activator test
    