# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: galacticfog/docker-sbt:latest

services:
  - postgres:9.4
  - galacticfog/test-ldap:0.1.0

variables:
  POSTGRES_DB: gestalt-security
  POSTGRES_USER: gestaltdev
  POSTGRES_PASSWORD: letmein
  DATABASE_HOSTNAME: postgres
  DATABASE_NAME: gestalt-security
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: gestaltdev
  DATABASE_PASSWORD: letmein
  ROOT_USERNAME: root
  ROOT_PASSWORD: letmein
  TEST_LDAP_URL: "ldap://galacticfog__test-ldap:389"
  TEST_LDAP_USER: admin
  TEST_LDAP_PASS: password
  
build:
  stage: build
  script:
    - ./activator clean update
    
  stage: test
  script:
    - ./activator test
    
